# SITE SETTINGS
title: ENRAM
author: ENRAM partners

# SOCIAL PROFILES
social:
  twitter: enram_network
  github: aloftdata/enram.eu

# THEME SETTINGS
theme: minima # Fallback theme
remote_theme: peterdesmet/petridish@3.1
posts_on_home: false
archive_permalink: false
github_edit: false
colors:
  links: "#87B547"
  banner: "#513266"
  footer: "#513266"
font_serif: false

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      type: "pages"
    values:
      background: /assets/backgrounds/default.jpg
  - scope:
      type: "posts"
    values:
      permalink: "/news/:year/:slug/"
